[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.3    unsupported  01:37:48Z

App                       Version  Status   Scale  Charm                     Channel        Rev  Address         Exposed  Message
data-integrator                    waiting      1  data-integrator           latest/edge     43  10.152.183.118  no       installing agent
mysql-k8s                          waiting      3  mysql-k8s                 8.0/edge       189  10.152.183.184  no       installing agent
mysql-router-k8s                   waiting      1  mysql-router-k8s                           0  10.152.183.195  no       installing agent
mysql-test-app            0.0.2    waiting      1  mysql-test-app            latest/edge     58  10.152.183.221  no       installing agent
self-signed-certificates           active       1  self-signed-certificates  latest/stable  155  10.152.183.73   no       

Unit                         Workload     Agent      Address       Ports  Message
data-integrator/0*           blocked      idle       10.1.118.200         Please relate the data-integrator with the desired product
mysql-k8s/0*                 maintenance  executing                       (install) installing charm software
mysql-k8s/1                  maintenance  executing                       (install) installing charm software
mysql-k8s/2                  maintenance  executing                       (install) installing charm software
mysql-router-k8s/0*          error        idle       10.1.118.203         hook failed: "certificates-relation-created"
mysql-test-app/0*            waiting      idle       10.1.118.201         
self-signed-certificates/0*  active       idle       10.1.118.202         

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

unit-mysql-router-k8s-0: 01:37:46 ERROR unit.mysql-router-k8s/0.juju-log certificates:9: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/./src/kubernetes_charm.py", line 312, in <module>
    ops.main.main(KubernetesRouterCharm)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 277, in _on_tls_relation_created
    self._relation.request_certificate_creation()
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 143, in request_certificate_creation
    csr = self._generate_csr(self.key.encode("utf-8"))
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 117, in _generate_csr
    return tls_certificates.generate_csr(
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/lib/charms/tls_certificates_interface/v2/tls_certificates.py", line 990, in generate_csr
    subject_name = [x509.NameAttribute(x509.NameOID.COMMON_NAME, subject)]
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/cryptography/x509/name.py", line 152, in __init__
    raise ValueError(msg)
ValueError: Attribute's length must be >= 1 and <= 64, but it was 68
unit-mysql-router-k8s-0: 01:37:47 ERROR juju.worker.uniter.operation hook "certificates-relation-created" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...