{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.1.77.12', port=49152): Max retries exceeded with url: /metrics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29a2da3850>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_exporter_endpoint","uid":"6e2a8ad806c4617b","parentUid":"12da8611c5b222141de6d5948456534b","status":"broken","time":{"start":1720489230988,"stop":1720489573939,"duration":342951},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":1,"retriesStatusChange":true,"parameters":[],"tags":["asyncio","abort_on_fail","@pytest.mark.skipif(False, reason='Requires amd64 architecture')","group(1)"]}],"uid":"12da8611c5b222141de6d5948456534b"},{"name":"asyncio.exceptions.TimeoutError","children":[{"name":"test_log_rotation","uid":"b451a099bd299f07","parentUid":"058a006597a0df056ad258eee876e9e4","status":"broken","time":{"start":1720489235191,"stop":1720490166908,"duration":931717},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":1,"retriesStatusChange":true,"parameters":[],"tags":["asyncio","abort_on_fail","group(1)"]}],"uid":"058a006597a0df056ad258eee876e9e4"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}