[32mINFO    [0m pytest_operator.plugin:plugin.py:734 Connecting to existing model concierge-microk8s:testing on unspecified cloud
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[32mINFO    [0m integration.test_charm:test_charm.py:45 Deploying mysql, mysqlrouter and application
[32mINFO    [0m juju.model:model.py:2284 Deploying ch:amd64/jammy/mysql-k8s-245
[32mINFO    [0m juju.model:model.py:2284 Deploying ch:amd64/jammy/mysql-test-app-73
[32mINFO    [0m juju.model:model.py:2284 Deploying local:mysql-router-k8s-0
[32mINFO    [0m integration.test_charm:test_charm.py:76 Waiting for mysqlrouter to be in BlockedStatus
[32mINFO    [0m integration.test_charm:test_charm.py:82 Relating mysql, mysqlrouter and application
[33mWARNING [0m juju.model:model.py:1666 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1666 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-router-k8s/0 [executing] maintenance: Waiting for container
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-router-k8s/0 [idle] maintenance: Waiting for container
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-router-k8s/0 [idle] maintenance: Waiting for container
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-router-k8s/0 [idle] waiting: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-router-k8s/0 [idle] waiting: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-router-k8s/0 [executing] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
  mysql-k8s/1 [idle] waiting: waiting to get cluster primary from peers
  mysql-k8s/2 [idle] active: 
  mysql-router-k8s/0 [idle] active: 
  mysql-test-app/0 [idle] active: Last written value=399
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [executing] active: Primary
  mysql-k8s/1 [executing] maintenance: joining the cluster
  mysql-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-router-k8s (waiting for exactly 2 units, current : 1)
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-router-k8s/0 [idle] active: 
  mysql-router-k8s/1 [executing] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-router-k8s/0 [idle] active: 
  mysql-router-k8s/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-router-k8s/0 [idle] active: 
  mysql-router-k8s/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-router-k8s/0 [idle] active: 
  mysql-router-k8s/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-router-k8s/0 [idle] active: 
  mysql-router-k8s/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-router-k8s/0 [idle] active: 
  mysql-router-k8s/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-router-k8s/0 [idle] active: 
  mysql-router-k8s/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-router-k8s/0 [idle] active: 
  mysql-router-k8s/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-router-k8s/0 [idle] active: 
  mysql-router-k8s/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-test-app (waiting for exactly 2 units, current : 1)
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-test-app/0 [idle] active: 
  mysql-test-app/1 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.4    unsupported  01:57:25Z

App               Version                  Status  Scale  Charm             Channel      Rev  Address         Exposed  Message
mysql-k8s         8.0.41-0ubuntu0.22.04.1  active      3  mysql-k8s         8.0/edge     245  10.152.183.253  no       
mysql-router-k8s  8.0.41-0ubuntu0.22.04.1  active      2  mysql-router-k8s                 0  10.152.183.90   no       
mysql-test-app    0.0.2                    active      2  mysql-test-app    latest/edge   73  10.152.183.232  no       

Unit                 Workload  Agent  Address      Ports  Message
mysql-k8s/0*         active    idle   10.1.71.206         Primary
mysql-k8s/1          active    idle   10.1.71.207         
mysql-k8s/2          active    idle   10.1.71.208         
mysql-router-k8s/0*  active    idle   10.1.71.201         
mysql-router-k8s/1   active    idle   10.1.71.209         
mysql-test-app/0*    active    idle   10.1.71.202         
mysql-test-app/1     active    idle   10.1.71.210         

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

unit-mysql-k8s-0: 01:49:15 ERROR unit.mysql-k8s/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 1056, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 970, in _on_update_status
    if self._is_cluster_blocked():
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 941, in _is_cluster_blocked
    member_state, _ = self._mysql.get_member_state()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 330, in wrapped_f
    return self(f, *args, **kw)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 467, in __call__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 368, in iter
    result = action(retry_state)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 410, in exc_check
    raise retry_exc.reraise()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 183, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 470, in __call__
    result = fn(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/mysql.py", line 2575, in get_member_state
    output = self._run_mysqlcli_script(
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/mysql_k8s_helpers.py", line 766, in _run_mysqlcli_script
    process = self.container.exec(command, timeout=timeout, stdin=password)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 2872, in exec
    return self._pebble.exec(
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 2884, in exec
    resp = self._request('POST', '/v1/exec', body=body)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1995, in _request
    response = self._request_raw(method, path, query, headers, data)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 2048, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/mysql/pebble.socket' (container restarted?)
unit-mysql-k8s-2: 01:49:16 ERROR unit.mysql-k8s/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/charm.py", line 1056, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/charm.py", line 970, in _on_update_status
    if self._is_cluster_blocked():
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/charm.py", line 941, in _is_cluster_blocked
    member_state, _ = self._mysql.get_member_state()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 330, in wrapped_f
    return self(f, *args, **kw)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 467, in __call__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 368, in iter
    result = action(retry_state)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 410, in exc_check
    raise retry_exc.reraise()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 183, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 470, in __call__
    result = fn(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/mysql.py", line 2575, in get_member_state
    output = self._run_mysqlcli_script(
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/mysql_k8s_helpers.py", line 766, in _run_mysqlcli_script
    process = self.container.exec(command, timeout=timeout, stdin=password)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 2872, in exec
    return self._pebble.exec(
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 2884, in exec
    resp = self._request('POST', '/v1/exec', body=body)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1995, in _request
    response = self._request_raw(method, path, query, headers, data)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 2048, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/mysql/pebble.socket' (container restarted?)
unit-mysql-k8s-1: 01:49:16 ERROR unit.mysql-k8s/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/charm.py", line 1056, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/charm.py", line 970, in _on_update_status
    if self._is_cluster_blocked():
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/charm.py", line 941, in _is_cluster_blocked
    member_state, _ = self._mysql.get_member_state()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 330, in wrapped_f
    return self(f, *args, **kw)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 467, in __call__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 368, in iter
    result = action(retry_state)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 410, in exc_check
    raise retry_exc.reraise()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 183, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 470, in __call__
    result = fn(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/mysql/v0/mysql.py", line 2575, in get_member_state
    output = self._run_mysqlcli_script(
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/mysql_k8s_helpers.py", line 766, in _run_mysqlcli_script
    process = self.container.exec(command, timeout=timeout, stdin=password)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 2872, in exec
    return self._pebble.exec(
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 2884, in exec
    resp = self._request('POST', '/v1/exec', body=body)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1995, in _request
    response = self._request_raw(method, path, query, headers, data)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 2048, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/mysql/pebble.socket' (container restarted?)
unit-mysql-k8s-0: 01:49:16 ERROR juju.worker.uniter.operation hook "update-status" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-2: 01:49:16 ERROR juju.worker.uniter.operation hook "update-status" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-1: 01:49:16 ERROR juju.worker.uniter.operation hook "update-status" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-0: 01:49:32 ERROR unit.mysql-k8s/0.juju-log Failed to execute MySQL cli command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/mysql_k8s_helpers.py", line 770, in _run_mysqlcli_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['/usr/bin/mysql', '-u', 'clusteradmin', '-p', '-N', '--socket=/var/run/mysqld/mysqld.sock', '-e', 'SELECT MEMBER_STATE, MEMBER_ROLE, MEMBER_ID, @@server_uuid FROM performance_schema.replication_group_members'], stdout='', stderr="Enter password: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\n"
unit-mysql-k8s-0: 01:49:32 ERROR unit.mysql-k8s/0.juju-log Failed to get member state: mysqld daemon is down
unit-mysql-k8s-1: 01:49:32 ERROR unit.mysql-k8s/1.juju-log Failed to execute MySQL cli command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/mysql_k8s_helpers.py", line 770, in _run_mysqlcli_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['/usr/bin/mysql', '-u', 'clusteradmin', '-p', '-N', '--socket=/var/run/mysqld/mysqld.sock', '-e', 'SELECT MEMBER_STATE, MEMBER_ROLE, MEMBER_ID, @@server_uuid FROM performance_schema.replication_group_members'], stdout='', stderr="Enter password: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\n"
unit-mysql-k8s-1: 01:49:32 ERROR unit.mysql-k8s/1.juju-log Failed to get member state: mysqld daemon is down
unit-mysql-k8s-2: 01:49:32 ERROR unit.mysql-k8s/2.juju-log Failed to execute MySQL cli command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/mysql_k8s_helpers.py", line 770, in _run_mysqlcli_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['/usr/bin/mysql', '-u', 'clusteradmin', '-p', '-N', '--socket=/var/run/mysqld/mysqld.sock', '-e', 'SELECT MEMBER_STATE, MEMBER_ROLE, MEMBER_ID, @@server_uuid FROM performance_schema.replication_group_members'], stdout='', stderr="Enter password: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\n"
unit-mysql-k8s-2: 01:49:32 ERROR unit.mysql-k8s/2.juju-log Failed to get member state: mysqld daemon is down
unit-mysql-k8s-0: 01:49:42 ERROR unit.mysql-k8s/0.juju-log Failed to execute MySQL cli command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/mysql_k8s_helpers.py", line 770, in _run_mysqlcli_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['/usr/bin/mysql', '-u', 'clusteradmin', '-p', '-N', '--socket=/var/run/mysqld/mysqld.sock', '-e', 'SELECT MEMBER_STATE, MEMBER_ROLE, MEMBER_ID, @@server_uuid FROM performance_schema.replication_group_members'], stdout='', stderr="Enter password: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\n"
unit-mysql-k8s-0: 01:49:42 ERROR unit.mysql-k8s/0.juju-log Failed to get member state: mysqld daemon is down
unit-mysql-k8s-0: 01:49:42 ERROR unit.mysql-k8s/0.juju-log Error getting member state while checking if cluster is blocked
unit-mysql-k8s-0: 01:49:42 ERROR unit.mysql-k8s/0.juju-log Failed to execute MySQL cli command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/mysql_k8s_helpers.py", line 770, in _run_mysqlcli_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['/usr/bin/mysql', '-u', 'clusteradmin', '-p', '-N', '--socket=/var/run/mysqld/mysqld.sock', '-e', 'SELECT MEMBER_STATE, MEMBER_ROLE, MEMBER_ID, @@server_uuid FROM performance_schema.replication_group_members'], stdout='', stderr="Enter password: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\n"
unit-mysql-k8s-0: 01:49:42 ERROR unit.mysql-k8s/0.juju-log Failed to get member state: mysqld daemon is down
unit-mysql-k8s-1: 01:49:42 ERROR unit.mysql-k8s/1.juju-log Failed to execute MySQL cli command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/mysql_k8s_helpers.py", line 770, in _run_mysqlcli_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['/usr/bin/mysql', '-u', 'clusteradmin', '-p', '-N', '--socket=/var/run/mysqld/mysqld.sock', '-e', 'SELECT MEMBER_STATE, MEMBER_ROLE, MEMBER_ID, @@server_uuid FROM performance_schema.replication_group_members'], stdout='', stderr="Enter password: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\n"
unit-mysql-k8s-1: 01:49:42 ERROR unit.mysql-k8s/1.juju-log Failed to get member state: mysqld daemon is down
unit-mysql-k8s-1: 01:49:42 ERROR unit.mysql-k8s/1.juju-log Error getting member state while checking if cluster is blocked
unit-mysql-k8s-2: 01:49:42 ERROR unit.mysql-k8s/2.juju-log Failed to execute MySQL cli command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/mysql_k8s_helpers.py", line 770, in _run_mysqlcli_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['/usr/bin/mysql', '-u', 'clusteradmin', '-p', '-N', '--socket=/var/run/mysqld/mysqld.sock', '-e', 'SELECT MEMBER_STATE, MEMBER_ROLE, MEMBER_ID, @@server_uuid FROM performance_schema.replication_group_members'], stdout='', stderr="Enter password: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\n"
unit-mysql-k8s-2: 01:49:42 ERROR unit.mysql-k8s/2.juju-log Failed to get member state: mysqld daemon is down
unit-mysql-k8s-2: 01:49:42 ERROR unit.mysql-k8s/2.juju-log Error getting member state while checking if cluster is blocked
unit-mysql-k8s-1: 01:49:42 ERROR unit.mysql-k8s/1.juju-log Failed to execute MySQL cli command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/mysql_k8s_helpers.py", line 770, in _run_mysqlcli_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['/usr/bin/mysql', '-u', 'clusteradmin', '-p', '-N', '--socket=/var/run/mysqld/mysqld.sock', '-e', 'SELECT MEMBER_STATE, MEMBER_ROLE, MEMBER_ID, @@server_uuid FROM performance_schema.replication_group_members'], stdout='', stderr="Enter password: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\n"
unit-mysql-k8s-1: 01:49:42 ERROR unit.mysql-k8s/1.juju-log Failed to get member state: mysqld daemon is down
unit-mysql-k8s-2: 01:49:42 ERROR unit.mysql-k8s/2.juju-log Failed to execute MySQL cli command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/mysql_k8s_helpers.py", line 770, in _run_mysqlcli_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['/usr/bin/mysql', '-u', 'clusteradmin', '-p', '-N', '--socket=/var/run/mysqld/mysqld.sock', '-e', 'SELECT MEMBER_STATE, MEMBER_ROLE, MEMBER_ID, @@server_uuid FROM performance_schema.replication_group_members'], stdout='', stderr="Enter password: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\n"
unit-mysql-k8s-2: 01:49:42 ERROR unit.mysql-k8s/2.juju-log Failed to get member state: mysqld daemon is down
unit-mysql-k8s-0: 01:49:52 ERROR unit.mysql-k8s/0.juju-log Failed to execute MySQL cli command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/mysql_k8s_helpers.py", line 770, in _run_mysqlcli_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['/usr/bin/mysql', '-u', 'clusteradmin', '-p', '-N', '--socket=/var/run/mysqld/mysqld.sock', '-e', 'SELECT MEMBER_STATE, MEMBER_ROLE, MEMBER_ID, @@server_uuid FROM performance_schema.replication_group_members'], stdout='', stderr="Enter password: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\n"
unit-mysql-k8s-0: 01:49:52 ERROR unit.mysql-k8s/0.juju-log Failed to get member state: mysqld daemon is down
unit-mysql-k8s-1: 01:49:52 ERROR unit.mysql-k8s/1.juju-log Failed to execute MySQL cli command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/mysql_k8s_helpers.py", line 770, in _run_mysqlcli_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['/usr/bin/mysql', '-u', 'clusteradmin', '-p', '-N', '--socket=/var/run/mysqld/mysqld.sock', '-e', 'SELECT MEMBER_STATE, MEMBER_ROLE, MEMBER_ID, @@server_uuid FROM performance_schema.replication_group_members'], stdout='', stderr="Enter password: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\n"
unit-mysql-k8s-1: 01:49:52 ERROR unit.mysql-k8s/1.juju-log Failed to get member state: mysqld daemon is down
unit-mysql-k8s-2: 01:49:52 ERROR unit.mysql-k8s/2.juju-log Failed to execute MySQL cli command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/mysql_k8s_helpers.py", line 770, in _run_mysqlcli_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['/usr/bin/mysql', '-u', 'clusteradmin', '-p', '-N', '--socket=/var/run/mysqld/mysqld.sock', '-e', 'SELECT MEMBER_STATE, MEMBER_ROLE, MEMBER_ID, @@server_uuid FROM performance_schema.replication_group_members'], stdout='', stderr="Enter password: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\n"
unit-mysql-k8s-2: 01:49:52 ERROR unit.mysql-k8s/2.juju-log Failed to get member state: mysqld daemon is down
unit-mysql-k8s-0: 01:50:02 ERROR unit.mysql-k8s/0.juju-log Failed to execute MySQL cli command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/mysql_k8s_helpers.py", line 770, in _run_mysqlcli_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['/usr/bin/mysql', '-u', 'clusteradmin', '-p', '-N', '--socket=/var/run/mysqld/mysqld.sock', '-e', 'SELECT MEMBER_STATE, MEMBER_ROLE, MEMBER_ID, @@server_uuid FROM performance_schema.replication_group_members'], stdout='', stderr="Enter password: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\n"
unit-mysql-k8s-0: 01:50:02 ERROR unit.mysql-k8s/0.juju-log Failed to get member state: mysqld daemon is down
unit-mysql-k8s-0: 01:50:02 ERROR unit.mysql-k8s/0.juju-log Error getting member state while checking if cluster is blocked
unit-mysql-k8s-1: 01:50:02 ERROR unit.mysql-k8s/1.juju-log Failed to execute MySQL cli command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/mysql_k8s_helpers.py", line 770, in _run_mysqlcli_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['/usr/bin/mysql', '-u', 'clusteradmin', '-p', '-N', '--socket=/var/run/mysqld/mysqld.sock', '-e', 'SELECT MEMBER_STATE, MEMBER_ROLE, MEMBER_ID, @@server_uuid FROM performance_schema.replication_group_members'], stdout='', stderr="Enter password: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\n"
unit-mysql-k8s-1: 01:50:02 ERROR unit.mysql-k8s/1.juju-log Failed to get member state: mysqld daemon is down
unit-mysql-k8s-1: 01:50:02 ERROR unit.mysql-k8s/1.juju-log Error getting member state while checking if cluster is blocked
unit-mysql-k8s-2: 01:50:02 ERROR unit.mysql-k8s/2.juju-log Failed to execute MySQL cli command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/mysql_k8s_helpers.py", line 770, in _run_mysqlcli_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['/usr/bin/mysql', '-u', 'clusteradmin', '-p', '-N', '--socket=/var/run/mysqld/mysqld.sock', '-e', 'SELECT MEMBER_STATE, MEMBER_ROLE, MEMBER_ID, @@server_uuid FROM performance_schema.replication_group_members'], stdout='', stderr="Enter password: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\n"
unit-mysql-k8s-2: 01:50:02 ERROR unit.mysql-k8s/2.juju-log Failed to get member state: mysqld daemon is down
unit-mysql-k8s-2: 01:50:02 ERROR unit.mysql-k8s/2.juju-log Error getting member state while checking if cluster is blocked

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...