[32mINFO    [0m pytest_operator.plugin:plugin.py:734 Connecting to existing model microk8s-localhost:test on unspecified cloud
[32mINFO    [0m integration.test_exporter_with_tls:test_exporter_with_tls.py:63 Deploying all the applications
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/mysql-test-app-58
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/mysql-k8s-189
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/grafana-agent-k8s-45
[32mINFO    [0m juju.model:model.py:2098 Deploying local:mysql-router-k8s-0
[32mINFO    [0m integration.test_exporter_with_tls:test_exporter_with_tls.py:100 Waiting for mysqlrouter to be in BlockedStatus
[32mINFO    [0m integration.test_exporter_with_tls:test_exporter_with_tls.py:106 Relating mysql, mysqlrouter and application
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mysql-router-k8s/0 [executing] waiting: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mysql-router-k8s/0 [idle] waiting: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mysql-router-k8s/0 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
  mysql-router-k8s/0 [idle] active: 
  mysql-test-app/0 [idle] active: 
[32mINFO    [0m integration.test_exporter_with_tls:test_exporter_with_tls.py:138 Deploying self-signed-certificates
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/self-signed-certificates-155
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  self-signed-certificates/0 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  self-signed-certificates/0 [idle] active: 
[32mINFO    [0m integration.test_exporter_with_tls:test_exporter_with_tls.py:149 Relating mysqlrouter with self-signed-certificates
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m integration.test_exporter_with_tls:test_exporter_with_tls.py:172 Relating mysqlrouter with grafana agent
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.3    unsupported  01:41:53Z

App                       Version                  Status   Scale  Charm                     Channel        Rev  Address         Exposed  Message
grafana-agent-k8s         0.32.1                   waiting      1  grafana-agent-k8s         latest/stable   45  10.152.183.125  no       installing agent
mysql-k8s                 8.0.37-0ubuntu0.22.04.3  active       1  mysql-k8s                 8.0/edge       189  10.152.183.136  no       
mysql-router-k8s          8.0.37-0ubuntu0.22.04.3  waiting      1  mysql-router-k8s                           0  10.152.183.246  no       installing agent
mysql-test-app            0.0.2                    active       1  mysql-test-app            latest/edge     58  10.152.183.228  no       
self-signed-certificates                           active       1  self-signed-certificates  latest/stable  155  10.152.183.59   no       

Unit                         Workload  Agent  Address      Ports  Message
grafana-agent-k8s/0*         blocked   idle   10.1.189.77         Missing incoming ('requires') relation
mysql-k8s/0*                 active    idle   10.1.189.75         Primary
mysql-router-k8s/0*          error     idle   10.1.189.73         hook failed: "certificates-relation-created"
mysql-test-app/0*            active    idle   10.1.189.72         
self-signed-certificates/0*  active    idle   10.1.189.78         

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

unit-mysql-router-k8s-0: 01:38:54 ERROR unit.mysql-router-k8s/0.juju-log certificates:10: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/./src/kubernetes_charm.py", line 312, in <module>
    ops.main.main(KubernetesRouterCharm)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 277, in _on_tls_relation_created
    self._relation.request_certificate_creation()
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 143, in request_certificate_creation
    csr = self._generate_csr(self.key.encode("utf-8"))
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 117, in _generate_csr
    return tls_certificates.generate_csr(
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/lib/charms/tls_certificates_interface/v2/tls_certificates.py", line 990, in generate_csr
    subject_name = [x509.NameAttribute(x509.NameOID.COMMON_NAME, subject)]
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/cryptography/x509/name.py", line 152, in __init__
    raise ValueError(msg)
ValueError: Attribute's length must be >= 1 and <= 64, but it was 68
unit-mysql-router-k8s-0: 01:38:55 ERROR juju.worker.uniter.operation hook "certificates-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-router-k8s-0: 01:39:01 ERROR unit.mysql-router-k8s/0.juju-log certificates:10: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/./src/kubernetes_charm.py", line 312, in <module>
    ops.main.main(KubernetesRouterCharm)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 277, in _on_tls_relation_created
    self._relation.request_certificate_creation()
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 143, in request_certificate_creation
    csr = self._generate_csr(self.key.encode("utf-8"))
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 117, in _generate_csr
    return tls_certificates.generate_csr(
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/lib/charms/tls_certificates_interface/v2/tls_certificates.py", line 990, in generate_csr
    subject_name = [x509.NameAttribute(x509.NameOID.COMMON_NAME, subject)]
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/cryptography/x509/name.py", line 152, in __init__
    raise ValueError(msg)
ValueError: Attribute's length must be >= 1 and <= 64, but it was 68
unit-mysql-router-k8s-0: 01:39:01 ERROR juju.worker.uniter.operation hook "certificates-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-router-k8s-0: 01:39:12 ERROR unit.mysql-router-k8s/0.juju-log certificates:10: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/./src/kubernetes_charm.py", line 312, in <module>
    ops.main.main(KubernetesRouterCharm)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 277, in _on_tls_relation_created
    self._relation.request_certificate_creation()
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 143, in request_certificate_creation
    csr = self._generate_csr(self.key.encode("utf-8"))
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 117, in _generate_csr
    return tls_certificates.generate_csr(
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/lib/charms/tls_certificates_interface/v2/tls_certificates.py", line 990, in generate_csr
    subject_name = [x509.NameAttribute(x509.NameOID.COMMON_NAME, subject)]
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/cryptography/x509/name.py", line 152, in __init__
    raise ValueError(msg)
ValueError: Attribute's length must be >= 1 and <= 64, but it was 68
unit-mysql-router-k8s-0: 01:39:12 ERROR juju.worker.uniter.operation hook "certificates-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-router-k8s-0: 01:39:34 ERROR unit.mysql-router-k8s/0.juju-log certificates:10: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/./src/kubernetes_charm.py", line 312, in <module>
    ops.main.main(KubernetesRouterCharm)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 277, in _on_tls_relation_created
    self._relation.request_certificate_creation()
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 143, in request_certificate_creation
    csr = self._generate_csr(self.key.encode("utf-8"))
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 117, in _generate_csr
    return tls_certificates.generate_csr(
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/lib/charms/tls_certificates_interface/v2/tls_certificates.py", line 990, in generate_csr
    subject_name = [x509.NameAttribute(x509.NameOID.COMMON_NAME, subject)]
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/cryptography/x509/name.py", line 152, in __init__
    raise ValueError(msg)
ValueError: Attribute's length must be >= 1 and <= 64, but it was 68
unit-mysql-router-k8s-0: 01:39:34 ERROR juju.worker.uniter.operation hook "certificates-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-router-k8s-0: 01:40:16 ERROR unit.mysql-router-k8s/0.juju-log certificates:10: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/./src/kubernetes_charm.py", line 312, in <module>
    ops.main.main(KubernetesRouterCharm)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 277, in _on_tls_relation_created
    self._relation.request_certificate_creation()
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 143, in request_certificate_creation
    csr = self._generate_csr(self.key.encode("utf-8"))
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 117, in _generate_csr
    return tls_certificates.generate_csr(
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/lib/charms/tls_certificates_interface/v2/tls_certificates.py", line 990, in generate_csr
    subject_name = [x509.NameAttribute(x509.NameOID.COMMON_NAME, subject)]
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/cryptography/x509/name.py", line 152, in __init__
    raise ValueError(msg)
ValueError: Attribute's length must be >= 1 and <= 64, but it was 68
unit-mysql-router-k8s-0: 01:40:17 ERROR juju.worker.uniter.operation hook "certificates-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-router-k8s-0: 01:41:39 ERROR unit.mysql-router-k8s/0.juju-log certificates:10: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/./src/kubernetes_charm.py", line 312, in <module>
    ops.main.main(KubernetesRouterCharm)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 277, in _on_tls_relation_created
    self._relation.request_certificate_creation()
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 143, in request_certificate_creation
    csr = self._generate_csr(self.key.encode("utf-8"))
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 117, in _generate_csr
    return tls_certificates.generate_csr(
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/lib/charms/tls_certificates_interface/v2/tls_certificates.py", line 990, in generate_csr
    subject_name = [x509.NameAttribute(x509.NameOID.COMMON_NAME, subject)]
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/cryptography/x509/name.py", line 152, in __init__
    raise ValueError(msg)
ValueError: Attribute's length must be >= 1 and <= 64, but it was 68
unit-mysql-router-k8s-0: 01:41:40 ERROR juju.worker.uniter.operation hook "certificates-relation-created" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...