[32mINFO    [0m pytest_operator.plugin:plugin.py:734 Connecting to existing model microk8s-localhost:test on unspecified cloud
[32mINFO    [0m integration.test_log_rotation:test_log_rotation.py:49 Deploying mysql, mysqlrouter and application
[32mINFO    [0m juju.model:model.py:2097 Deploying ch:amd64/jammy/mysql-test-app-46
[32mINFO    [0m juju.model:model.py:2097 Deploying ch:amd64/jammy/mysql-k8s-162
[32mINFO    [0m juju.model:model.py:2097 Deploying local:jammy/mysql-router-k8s-0
[32mINFO    [0m integration.test_log_rotation:test_log_rotation.py:80 Waiting for mysqlrouter to be in BlockedStatus
[32mINFO    [0m integration.test_log_rotation:test_log_rotation.py:86 Relating mysql, mysqlrouter and application
[33mWARNING [0m juju.model:model.py:1563 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1563 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m integration.test_log_rotation:test_log_rotation.py:107 Stopping the logrotate executor pebble service
[32mINFO    [0m integration.test_log_rotation:test_log_rotation.py:110 Stopping any running logrotate jobs
[32mINFO    [0m integration.test_log_rotation:test_log_rotation.py:113 Removing existing archive directory
[32mINFO    [0m integration.test_log_rotation:test_log_rotation.py:120 Writing some data mysqlrouter log file
[32mINFO    [0m integration.test_log_rotation:test_log_rotation.py:124 Ensuring only log files exist
[32mINFO    [0m integration.test_log_rotation:test_log_rotation.py:133 Executing logrotate
[32mINFO    [0m integration.test_log_rotation:test_log_rotation.py:136 Ensuring log files and archive directories exist
[32mINFO    [0m integration.test_log_rotation:test_log_rotation.py:147 Ensuring log files was rotated
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.3    unsupported  01:40:20Z

App               Version                  Status   Scale  Charm             Channel      Rev  Address         Exposed  Message
mysql-k8s         8.0.37-0ubuntu0.22.04.3  waiting      3  mysql-k8s         8.0/edge     162  10.152.183.146  no       installing agent
mysql-router-k8s  8.0.37-0ubuntu0.22.04.3  active       1  mysql-router-k8s                 0  10.152.183.178  no       
mysql-test-app    0.0.2                    active       1  mysql-test-app    latest/edge   46  10.152.183.223  no       Last written value=147

Unit                 Workload     Agent      Address     Ports  Message
mysql-k8s/0          maintenance  idle       10.1.95.79         joining the cluster
mysql-k8s/1*         active       executing  10.1.95.78         Primary
mysql-k8s/2          active       executing  10.1.95.77         
mysql-router-k8s/0*  active       idle       10.1.95.73         
mysql-test-app/0*    active       idle       10.1.95.72         Last written value=147

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

unit-mysql-k8s-1: 01:39:07 ERROR unit.mysql-k8s/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/./src/charm.py", line 861, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 548, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 527, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 516, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 647, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/relations/mysql_provider.py", line 211, in _configure_endpoints
    if not relations or not self.charm.unit_initialized:
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/mysql/v0/mysql.py", line 635, in unit_initialized
    return self._mysql.cluster_metadata_exists(self.get_unit_address(self.unit))
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 647, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/mysql/v0/mysql.py", line 1413, in cluster_metadata_exists
    output = self._run_mysqlsh_script("\n".join(check_cluster_metadata_commands))
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 647, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/mysql_k8s_helpers.py", line 594, in _run_mysqlsh_script
    self.container.push(path=MYSQLSH_SCRIPT_FILE, source=script)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/model.py", line 2390, in push
    self._pebble.push(
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/pebble.py", line 2358, in push
    response = self._request_raw('POST', '/v1/files', None, headers, data)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/ops/pebble.py", line 1912, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/mysql/pebble.socket' (container restarted?)
unit-mysql-k8s-1: 01:39:08 ERROR juju.worker.uniter.operation hook "leader-elected" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...