[32mINFO    [0m integration.helpers:helpers.py:549 Ensure continuous writes are incrementing
[32mINFO    [0m integration.helpers:helpers.py:501 Retrieving primary unit
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:177 Creating invalid upgrade charm
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:180 Refreshing mysql router with an invalid charm
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:183 Wait for upgrade to fail
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:194 Ensure continuous writes while in failure state
[32mINFO    [0m integration.helpers:helpers.py:549 Ensure continuous writes are incrementing
[32mINFO    [0m integration.helpers:helpers.py:501 Retrieving primary unit
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:197 Re-refresh the charm
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:202 Running resume-upgrade on the mysql router leader unit
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:206 Wait for the charm to be rolled back
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-router-k8s/0 [idle] active: Router 8.0.36+testupgrade running (restart pending); Charmed operator 1.2+d6f3e57
  mysql-router-k8s/1 [idle] active: Router 8.0.36+testupgrade running (restart pending); Charmed operator 1.2+d6f3e57
  mysql-router-k8s/2 [idle] active: Router 8.0.36+testupgrade running; Charmed operator 1.2+d6f3e57
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-router-k8s/0 [idle] active: Router 8.0.36+testupgrade running (restart pending); Charmed operator 1.2+d6f3e57
  mysql-router-k8s/1 [executing] maintenance: 
  mysql-router-k8s/2 [idle] active: Router 8.0.36+testupgrade running; Charmed operator 1.2+d6f3e57
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-router-k8s/0 [executing] maintenance: 
  mysql-router-k8s/1 [idle] active: 
  mysql-router-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-router-k8s/0 [idle] active: 
  mysql-router-k8s/1 [idle] active: 
  mysql-router-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-router-k8s/0 [idle] active: 
  mysql-router-k8s/1 [idle] active: 
  mysql-router-k8s/2 [idle] active: 
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:225 Ensure continuous writes after rollback procedure
[32mINFO    [0m integration.helpers:helpers.py:549 Ensure continuous writes are incrementing
[32mINFO    [0m integration.helpers:helpers.py:501 Retrieving primary unit
[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.3    unsupported  01:45:11Z

App               Version                  Status  Scale  Charm             Channel      Rev  Address         Exposed  Message
mysql-k8s         8.0.36-0ubuntu0.22.04.1  active      1  mysql-k8s         8.0/edge     150  10.152.183.212  no       
mysql-router-k8s  8.0.36-0ubuntu0.22.04.1  active      3  mysql-router-k8s  8.0/edge       2  10.152.183.118  no       
mysql-test-app    0.0.2                    active      1  mysql-test-app    latest/edge   38  10.152.183.201  no       

Unit                 Workload  Agent  Address      Ports  Message
mysql-k8s/0*         active    idle   10.1.61.205         Primary
mysql-router-k8s/0   active    idle   10.1.61.212         
mysql-router-k8s/1   active    idle   10.1.61.211         
mysql-router-k8s/2*  active    idle   10.1.61.210         
mysql-test-app/0*    active    idle   10.1.61.200         

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:


[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...
[31m[1mERROR   [0m websockets.client:protocol.py:1015 data transfer failed
Traceback (most recent call last):
  File "/home/runner/work/mysql-router-k8s-operator/mysql-router-k8s-operator/.tox/integration/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 959, in transfer_data
    message = await self.read_message()
  File "/home/runner/work/mysql-router-k8s-operator/mysql-router-k8s-operator/.tox/integration/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1029, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/runner/work/mysql-router-k8s-operator/mysql-router-k8s-operator/.tox/integration/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1104, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/runner/work/mysql-router-k8s-operator/mysql-router-k8s-operator/.tox/integration/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1161, in read_frame
    frame = await Frame.read(
  File "/home/runner/work/mysql-router-k8s-operator/mysql-router-k8s-operator/.tox/integration/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/usr/lib/python3.10/asyncio/streams.py", line 708, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 924, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor
[33mWARNING [0m juju.client.connection:connection.py:657 RPC: Connection closed, reconnecting